### ISSUE TITLE
Add big milestones for Fall 2019 + Spring 2020

### ISSUE THREAD

**Issue by karpawich** [GTBitsOfGood/website#85]
Introduce new milestones for Fall 2019 and/or Spring 2020. Some examples include:

- [ ] Designers introduced
- [ ] BoG becomes SGA org
- [ ] Bootcamp splits into backend/frontend
- [ ] Launch party created
